name: Auto Green
on:
  schedule:
    - cron: "0 * * * *"
jobs:
   commit:
    name: Auto Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com" && git config --global user.name "${GITHUB_ACTOR}" && git commit --allow-empty -m "a commit every day, keep your girlfriend far away" && git push
